version: "3.3"

services:
  youqel-db:
    image: postgres:9.4
    environment:
      - POSTGRES_DB=youqel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - youqel-net
    ports:
      - "5432:5432"  
    volumes:
      - type: volume
        source: dbdata
        target: /data/youqel-db

  youqel-backend:
    image: ymadkour/youqel-backend:latest
    ports:
      - "10280:3000"
    depends_on:
          - youqel-db
    networks:
      - youqel-net
    environment:
      - YOUQEL_BASEURL=http://www.youqel.com
      - DEBUG=app:*
      - db.youqel.jdbc.driver=org.postgresql.Driver
      - db.youqel.jdbc.url=jdbc:postgresql://youqel-db:5432/youqel
      - db.youqel.jdbc.user=postgres
      - db.youqel.jdbc.password=postgres

  youqel-frontend:
    image: ymadkour/youqel-frontend:latest
    ports:
      - "80:80"
    networks:
      - youqel-net
    environment:
      - YOUQEL_BASEURL=http://www.youqel.com:10280
networks:
  youqel-net:

volumes:
  dbdata: